FROM node:16-alpine
WORKDIR /app
COPY ./package.json ./
RUN npm install
COPY ./ ./

ARG NODE_ENV
ENV NODE_ENV $NODE_ENV

CMD if [ "$NODE_ENV" = "development" ]; then \
    npm run start:dev; \
  else \
    npm run start:prod; \
  fi
